In [1]:
 import numpy as np

In [2]:
x = np.array([1,2,3,4], dtype=np.float)
print(x)

[1. 2. 3. 4.]


In [5]:
y = 2.0 * x + 2
print(y)

[ 4.  6.  8. 10.]


In [6]:
z = np.sin(x)
print(z)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [7]:
q = x + y * 3
print(q)

[13. 20. 27. 34.]


In [9]:
print("平均: ",np.mean(x))
print("分散: ",np.var(x))
print("最大: ",np.max(x))
print("最小: "np.min(x))


平均:  2.5
分散:  1.25
最大:  4.0
最小:  1.0


In [12]:
e = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]],dtype=np.float)
print(e)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [13]:
print(e.shape)

(3, 3)


In [15]:
print("全集計: ",np.max(e))
print("行集計: ",np.max(e,axis=1))
print("列集計: ",np.max(e,axis=0))

全集計:  9.0
行集計:  [3. 6. 9.]
列集計:  [7. 8. 9.]
